apiVersion: v1 
kind: Service
metadata:
 name: noderedrepo-3
spec:
 type: LoadBalancer
 selector:
  app: noderedrepo-3
 ports:
 - protocol: TCP
   port: 80
   targetPort: 1880
---
kind: Deployment
apiVersion: apps/v1
metadata:
 name: noderedrepo-3
spec:
 replicas: 1
 selector:
  matchLabels:
   app: noderedrepo-3
 template:
  metadata:
   labels:
    app: noderedrepo-3
  spec:
   containers:
   - name: nodered-cluster
     image: gcr.io/synapses-323217/github.com/misbahhassan08/noderedrepo-3:latest
     ports:
     - containerPort: 1880